"""balances net worth recurring notifications

Revision ID: 52731efd5fc9
Revises: d82493816af4
Create Date: 2026-08-11 16:59:27.860547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52731efd5fc9'
down_revision: Union[str, None] = 'd82493816af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('dedup_key', sa.String(length=255), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedup_key', name='uq_notification_dedup')
    )
    op.create_index(op.f('ix_notification_log_user_id'), 'notification_log', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('budget_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('budget_threshold_pct', sa.Float(), nullable=False),
    sa.Column('budget_alert_at_100', sa.Boolean(), nullable=False),
    sa.Column('bill_reminders_enabled', sa.Boolean(), nullable=False),
    sa.Column('bill_lead_days', sa.Integer(), nullable=False),
    sa.Column('fraud_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('weekly_digest_enabled', sa.Boolean(), nullable=False),
    sa.Column('weekly_digest_day', sa.Integer(), nullable=False),
    sa.Column('email_override', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('recurring_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('merchant_key', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('cadence', sa.String(length=16), nullable=False),
    sa.Column('median_gap_days', sa.Float(), nullable=False),
    sa.Column('expected_amount', sa.Float(), nullable=False),
    sa.Column('amount_stability', sa.String(length=16), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.Date(), nullable=False),
    sa.Column('last_seen', sa.Date(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'merchant_key', name='uq_recurring_user_merchant')
    )
    op.create_index(op.f('ix_recurring_series_merchant_key'), 'recurring_series', ['merchant_key'], unique=False)
    op.create_index(op.f('ix_recurring_series_next_due_date'), 'recurring_series', ['next_due_date'], unique=False)
    op.create_index(op.f('ix_recurring_series_user_id'), 'recurring_series', ['user_id'], unique=False)
    op.create_table('account_balance_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=True),
    sa.Column('available_balance', sa.Float(), nullable=True),
    sa.Column('credit_limit', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'date', name='uq_snapshot_account_date')
    )
    op.create_index(op.f('ix_account_balance_snapshots_account_id'), 'account_balance_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_balance_snapshots_date'), 'account_balance_snapshots', ['date'], unique=False)
    op.add_column('accounts', sa.Column('available_balance', sa.Float(), nullable=True))
    op.add_column('accounts', sa.Column('credit_limit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'credit_limit')
    op.drop_column('accounts', 'available_balance')
    op.drop_index(op.f('ix_account_balance_snapshots_date'), table_name='account_balance_snapshots')
    op.drop_index(op.f('ix_account_balance_snapshots_account_id'), table_name='account_balance_snapshots')
    op.drop_table('account_balance_snapshots')
    op.drop_index(op.f('ix_recurring_series_user_id'), table_name='recurring_series')
    op.drop_index(op.f('ix_recurring_series_next_due_date'), table_name='recurring_series')
    op.drop_index(op.f('ix_recurring_series_merchant_key'), table_name='recurring_series')
    op.drop_table('recurring_series')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_notification_log_user_id'), table_name='notification_log')
    op.drop_table('notification_log')
    # ### end Alembic commands ###
