"""sync preferences

Revision ID: cd70034c122e
Revises: ea58d06321b3
Create Date: 2026-08-12 17:42:59.820693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd70034c122e'
down_revision: Union[str, None] = 'ea58d06321b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('auto_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('interval_hours', sa.Integer(), nullable=False),
    sa.Column('last_auto_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_auto_sync_status', sa.String(length=16), nullable=True),
    sa.Column('last_auto_sync_detail', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_preferences')
    # ### end Alembic commands ###
